### PR TITLE
stuff

### PR DESCRIPTION
**Pull request by wyvest**

### CODE REVIEW

**Review by isXander — CHANGES_REQUESTED** [review]
I love this feature but I think you should just keep the hypixel compatability mode setting. There is really no point in using it otherwise. Also, there is no point in creating a server ping field because you can just get that through the server data in the element itself.

**Review by isXander — CHANGES_REQUESTED** [review]
Also change the keybind name back!

**Comment by wyvest** [comment]
> I love this feature but I think you should just keep the hypixel compatability mode setting. There is really no point in using it otherwise. Also, there is no point in creating a server ping field because you can just get that through the server data in the element itself.

iirc i did it how you did it sooooo


> Also change the keybind name back!

the reason i changed it is because it causes incompatibilities - see https://github.com/shatter-point/Revamped-TimeChanger/issues/3

**Comment by isXander** [comment]
> > I love this feature but I think you should just keep the hypixel compatability mode setting. There is really no point in using it otherwise. Also, there is no point in creating a server ping field because you can just get that through the server data in the element itself.
> 
> iirc i did it how you did it sooooo
> 
> > Also change the keybind name back!
> 
> the reason i changed it is because it causes incompatibilities - see [shatter-point/Revamped-TimeChanger#3](https://github.com/shatter-point/Revamped-TimeChanger/issues/3)

I'm talking about `useServerListPinger` keep the hypixel one tho

**Comment by isXander** [comment]
implemented in 9afb109

**Pull request closed without merging**
